### ISSUE TITLE
Should `OfferRequestSlice` `origin` and `destination` be type `Place`?

### ISSUE THREAD

**Issue by nathanlindsay** [duffelhq/duffel-api-javascript#657]
Me again... Really sorry!

```typescript
interface OfferRequestSlice {
    ...
    /**
     * The city or airport the passengers want to travel to
     */
    destination: Place | string;
    /**
     * The city or airport the passengers want to depart from
     */
    origin: Place | string;
   ....
}
```

Should these just be set to `Place`? Is there an example of a time when these might be a string?

**Comment by shaundon** [comment]
Hey – I'm not 100% on this, I _think_ there may be use cases where it's appropriate to use a string, so it may be best to leave it as is.

**Comment by igorp1** [comment]
Hey @nathanlindsay! I'll be closing this for now since there hasn't been any activity, but please feel free to re-open if you have any other question. To clarify, we do seem to reuse the `OfferRequestSlice ` type on the `CreateOfferRequest` type. `CreateOfferRequest` is used for the payload, where your input and destination are strings with the iata code.That's why we have `origin` and  `destination` as either `Place` or `string`
