### ISSUE TITLE
Stays cheapest rate and amount typing inconsistent with docs

### ISSUE THREAD

**Issue by Tom-Carpendale** [duffelhq/duffel-api-javascript#975]
Hi, in the [docs](https://duffel.com/docs/api/v2/search-result/schema), it states that fields like the `cheapest_rate_currency` and `cheapest_rate_total_amount` are on the search result itself. However, the Typescript typings put this on the accommodation:
```ts
export interface StaysAccommodation {
...
  /**
   * The total currency for the cheapest rate for this accommodation, as an ISO 4217 currency code. If rooms data is available, this is equivalent to the cheapest rate for the cheapest room.
   */
  cheapest_rate_currency: string;
  /**
   * The total amount for the cheapest rate for this accommodation. If rooms data is available, this is equivalent to the cheapest rate for the cheapest room.
   */
  cheapest_rate_total_amount: string;
...
}
```

I also checked on the Duffel dashboard using the networking tab, but it appears here the data is actually present in both locations?

```
{
    "data": {
        "createdAt": "2024-10-30T11:06:23.801457Z",
        "results": [
            {
                "cheapestRateTotalAmount": "899.00",
                "cheapestRateCurrency": "GBP",
                ...
                "accommodation": {
                    "cheapestRateTotalAmount": "899.00",
                    "cheapestRateCurrency": "GBP",
                    ...
                },
                "checkInDate": "2024-12-30",
                "id": "srr_0000AnWv6i821GQkyeEi9I"
            }
        ]
    }
}
```

I'm not sure which of these is how the data is actually supposed to be laid out.

Thanks!

**Comment by jekku** [comment]
Hello @Tom-Carpendale 👋🏽 Thanks for raising this and apologies for the confusion. I will try and explain why this is currently the case.

We have [introduced Duffel API's V2](https://changelog.duffel.com/announcements/introducing-v2-of-the-duffel-api), which includes a [migration guide](https://duffel.com/docs/guides/migrating-api-version-from-v1-to-v2).

This means many fields that used to be in V1 will no longer be in V2, and some fields in V2 are new and will not be backported to V1. Part of this is cheapest rate information within accommodation.

The latest version of duffel-api-javascript assumes V2 types, payload and return values, too.

The Duffel Dashboard will very soon move to requesting and using V2 of the API.

My short recommendation is to use the latest version of duffel-api-javascript in order to use V2 effectively. (Notice how the [StaysAccommodation](https://github.com/duffelhq/duffel-api-javascript/blob/main/src/Stays/StaysTypes.ts#L302) interface in main is different)

When reading the documentation, also make sure that you are[ using the V2 documentation](https://duffel.com/docs/api/v2/accommodation/schema). A dropdown in the upper left indicates the current version you are on:

![image](https://github.com/user-attachments/assets/4868fd0e-cf38-4e42-a033-04c9262aba02)

If there are any more questions just let me know in this issue. I am closing for now but feel free to re-open if there's anything related and outstanding.
